version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3308:3308
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: mypassql
    volumes:
      - microservices_devdojo:/usr/src/mysql

volumes:
  microservices_devdojo:
